export const countryCenters = {
  'China': [104.1954, 35.8617],
  'United States': [-95.7129, 37.0902],
  'Japan': [138.2529, 36.2048],
  'South Korea': [127.7669, 35.9078],
  'United Kingdom': [-3.4360, 55.3781],
  'France': [2.2137, 46.2276],
  'Germany': [10.4515, 51.1657],
  'Italy': [12.5674, 41.8719],
  'Spain': [-3.7492, 40.4637],
  'Russia': [105.3188, 61.5240],
  'Canada': [-106.3468, 56.1304],
  'Australia': [133.7751, -25.2744],
  'Brazil': [-51.9253, -14.2350],
  'India': [78.9629, 20.5937],
  'South Africa': [22.9375, -30.5595],
  'United Arab Emirates': [53.8478, 23.4241],
  'Singapore': [103.8198, 1.3521],
  'Thailand': [100.9925, 15.8700],
  'Malaysia': [101.9758, 4.2105],
  'Indonesia': [113.9213, -0.7893],
  'Vietnam': [108.2772, 14.0583],
  'Philippines': [121.7740, 12.8797],
  'Mexico': [-102.5528, 23.6345],
  'Argentina': [-63.6167, -38.4161],
  'Egypt': [30.8025, 26.8206],
  'Nigeria': [8.6753, 9.0820],
  'Kenya': [37.9062, -0.0236],
  'Netherlands': [5.2913, 52.1326],
  'Belgium': [4.4699, 50.5039],
  'Switzerland': [8.2275, 46.8182],
  'Sweden': [18.6435, 60.1282],
  'Norway': [8.4689, 60.4720],
  'Denmark': [9.5018, 56.2639],
  'Finland': [25.7482, 61.9241],
  'Poland': [19.1451, 51.9194],
  'Turkey': [35.2433, 38.9637],
  'Israel': [34.8516, 31.0461],
  'Saudi Arabia': [45.0792, 23.8859],
  'Iran': [53.6880, 32.4279],
  'Pakistan': [73.0479, 30.3753],
  'Bangladesh': [90.3563, 23.6850],
  'New Zealand': [174.8860, -40.9006],
  'Ireland': [-8.2439, 53.4129],
  'Austria': [13.3439, 47.2701],
  'Portugal': [-8.2245, 39.3999],
  'Greece': [21.8243, 39.0742],
  'Czech Republic': [15.4729, 49.8175],
  'Hungary': [19.5033, 47.1625],
  'Romania': [24.9668, 45.9432],
  'Bulgaria': [25.6050, 42.7339],
  'Croatia': [15.2000, 45.1000],
  'Slovakia': [19.6435, 48.6690],
  'Slovenia': [14.5146, 46.1512],
  'Estonia': [25.0000, 58.5000],
  'Latvia': [24.5000, 57.0000],
  'Lithuania': [24.0000, 55.0000],
  'Cyprus': [33.3638, 35.1264],
  'Malta': [14.5146, 35.8989],
  'Serbia': [21.0000, 44.0000],
  'Bosnia and Herzegovina': [18.5000, 44.0000],
  'Albania': [20.0000, 41.0000],
  'North Macedonia': [21.5000, 41.8000],
  'Ukraine': [31.1656, 48.3794],
  'Belarus': [27.5667, 53.7000],
  'Moldova': [28.3699, 47.4116],
  'Kazakhstan': [68.3832, 48.0196],
  'Uzbekistan': [64.5853, 41.3775],
  'Kyrgyzstan': [74.5800, 41.2044],
  'Tajikistan': [71.5000, 39.0000],
  'Turkmenistan': [59.5500, 38.0000],
  'Azerbaijan': [47.7873, 40.1431],
  'Georgia': [43.3569, 42.3154],
  'Armenia': [44.5136, 40.0691],
  'Afghanistan': [67.7099, 33.9399],
  'Mongolia': [106.9183, 46.8625],
  'Myanmar': [95.9560, 21.9162],
  'Cambodia': [104.9167, 12.5657],
  'Laos': [102.4955, 19.8563],
  'Sri Lanka': [80.7718, 7.8731],
  'Nepal': [84.1240, 28.3949],
  'Bhutan': [89.6787, 27.5146],
  'Maldives': [73.2207, 3.2028],
  'Iraq': [43.8317, 33.2232],
  'Syria': [38.9968, 34.8021],
  'Jordan': [35.9375, 30.5852],
  'Lebanon': [35.8989, 33.8547],
  'Palestine': [35.2332, 31.5000],
  'Yemen': [47.5868, 15.5527],
  'Oman': [57.0259, 21.5126],
  'Kuwait': [47.4979, 29.3117],
  'Bahrain': [50.5577, 26.0275],
  'Qatar': [51.5310, 25.3548],
  'Morocco': [-7.0926, 31.7917],
  'Algeria': [2.6319, 28.0339],
  'Tunisia': [9.5375, 33.8869],
  'Libya': [17.2283, 26.3351],
  'Sudan': [30.2176, 12.8628],
  'Ethiopia': [38.7469, 9.1450],
  'Somalia': [46.1996, 5.1521],
  'Djibouti': [42.5903, 11.8251],
  'Eritrea': [39.2833, 15.1794],
  'Uganda': [32.2903, 1.3733],
  'Tanzania': [34.8888, -6.3690],
  'Rwanda': [29.8739, -1.9403],
  'Burundi': [30.3313, -3.3731],
  'Malawi': [34.3015, -13.2543],
  'Zambia': [27.8493, -13.1339],
  'Zimbabwe': [29.1549, -19.0154],
  'Botswana': [24.6849, -22.3285],
  'Namibia': [17.9473, -22.9576],
  'Lesotho': [28.2333, -29.6099],
  'Swaziland': [31.8650, -26.5225],
  'Mozambique': [35.5296, -18.6657],
  'Angola': [17.5374, -11.2027],
  'Congo': [15.8271, -0.2280],
  'Democratic Republic of the Congo': [23.8597, -4.0383],
  'Cameroon': [12.3547, 7.3697],
  'Ghana': [-1.0232, 7.9465],
  'Ivory Coast': [-5.5471, 7.5399],
  'Benin': [2.3515, 9.3077],
  'Togo': [1.2227, 8.6195],
  'Senegal': [-14.4524, 14.4974],
  'Mali': [-7.6921, 17.5707],
  'Mauritania': [-10.9408, 20.9373],
  'Gambia': [-15.3101, 13.4667],
  'Guinea-Bissau': [-14.4363, 11.8037],
  'Guinea': [-9.6966, 10.7480],
  'Liberia': [-9.4295, 6.4281],
  'Sierra Leone': [-11.7799, 8.4606],
  'Costa Rica': [-83.4233, 9.7489],
  'Panama': [-79.3470, 8.5380],
  'Haiti': [-72.3370, 18.9712],
  'Dominican Republic': [-70.6693, 18.7357],
  'Cuba': [-77.7812, 21.5218],
  'Jamaica': [-77.2975, 18.1096],
  'Bahamas': [-77.3308, 24.2508],
  'Barbados': [-59.5236, 13.1939],
  'Trinidad and Tobago': [-61.2225, 10.6918],
  'Guyana': [-58.1552, 4.8604],
  'Suriname': [-55.1668, 3.9193],
  'Peru': [-75.0152, -9.1899],
  'Colombia': [-73.9857, 4.5709],
  'Venezuela': [-66.9036, 6.4238],
  'Chile': [-71.5430, -35.6751],
  'Ecuador': [-78.1834, -1.8312],
  'Bolivia': [-68.1500, -16.2902],
  'Paraguay': [-58.4433, -23.4425],
  'Uruguay': [-55.7658, -32.5228],
  'Papua New Guinea': [143.9555, -6.3149],
  'Fiji': [178.0650, -17.7134],
  'Samoa': [-172.1648, -13.7590],
  'Tonga': [-175.3484, -21.1789],
  'Solomon Islands': [160.1562, -9.6457],
  'Vanuatu': [166.9592, -15.3767],
  'New Caledonia': [165.6180, -21.5218],
  'French Polynesia': [-149.6667, -17.5000],
  'Iceland': [-19.0208, 64.9631],
  'Greenland': [-40.0000, 72.0000],
  'Faroe Islands': [-6.8000, 61.9000],
  'Svalbard': [16.0000, 78.0000]
};

export const countryNameAliases = {
  'USA': 'United States',
  'United States of America': 'United States',
  'U.S.A.': 'United States',
  'U.S.': 'United States',
  'America': 'United States',
  'UK': 'United Kingdom',
  'Great Britain': 'United Kingdom',
  'Britain': 'United Kingdom',
  'UAE': 'United Arab Emirates',
  'Korea': 'South Korea',
  'South Korea Republic': 'South Korea',
  'ROK': 'South Korea',
  'PRC': 'China',
  'People\'s Republic of China': 'China',
  'Republic of China': 'China',
  'Taiwan': 'China',
  'Hong Kong': 'China',
  'Macau': 'China',
  'Czechia': 'Czech Republic',
  'Czech': 'Czech Republic',
  'Slovak Republic': 'Slovakia',
  'Slovak': 'Slovakia',
  'Bosnia': 'Bosnia and Herzegovina',
  'Macedonia': 'North Macedonia',
  'FYROM': 'North Macedonia',
  'Serbia and Montenegro': 'Serbia',
  'East Timor': 'Timor-Leste',
  'Timor': 'Timor-Leste',
  'São Tomé and Príncipe': 'Sao Tome and Principe',
  'Sao Tome': 'Sao Tome and Principe',
  'DRC': 'Democratic Republic of the Congo',
  'Congo-Kinshasa': 'Democratic Republic of the Congo',
  'Congo-Brazzaville': 'Congo',
  'Ivory Coast': 'Cote d\'Ivoire',
  'Cote d\'Ivoire': 'Ivory Coast',
  'Burma': 'Myanmar',
  'Myanmar Burma': 'Myanmar',
  'Laos': 'Lao People\'s Democratic Republic',
  'Lao': 'Laos',
  'Khmer': 'Cambodia',
  'Cambodia Kampuchea': 'Cambodia',
  'Kampuchea': 'Cambodia',
  'North Korea': 'Korea, Democratic People\'s Republic of',
  'DPRK': 'Korea, Democratic People\'s Republic of',
  'South Korea': 'Korea, Republic of',
  'South Sudan': 'South Sudan',
  'Sudan (North)': 'Sudan',
  'Swaziland': 'Eswatini',
  'Eswatini': 'Swaziland',
  'Lesotho Kingdom': 'Lesotho',
  'Namibia South West Africa': 'Namibia',
  'Botswana Bechuanaland': 'Botswana',
  'Zimbabwe Rhodesia': 'Zimbabwe',
  'Zambia Northern Rhodesia': 'Zambia',
  'Malawi Nyasaland': 'Malawi',
  'Tanzania Tanganyika': 'Tanzania',
  'Uganda Protectorate': 'Uganda',
  'Kenya Colony': 'Kenya',
  'Ethiopia Abyssinia': 'Ethiopia',
  'Somali Republic': 'Somalia',
  'Djibouti French Territory': 'Djibouti',
  'Eritrea Ethiopia': 'Eritrea',
  'Morocco Kingdom': 'Morocco',
  'Algeria': 'Algeria',
  'Tunisia': 'Tunisia',
  'Libya': 'Libya',
  'Egypt Arab Republic': 'Egypt',
  'Israel State': 'Israel',
  'Palestine State': 'Palestine',
  'Jordan Hashemite Kingdom': 'Jordan',
  'Syria Arab Republic': 'Syria',
  'Lebanon': 'Lebanon',
  'Iraq Republic': 'Iraq',
  'Iran Islamic Republic': 'Iran',
  'Saudi Arabia Kingdom': 'Saudi Arabia',
  'Yemen Republic': 'Yemen',
  'Oman Sultanate': 'Oman',
  'Kuwait State': 'Kuwait',
  'Bahrain Kingdom': 'Bahrain',
  'Qatar State': 'Qatar',
  'UAE Emirates': 'United Arab Emirates',
  'Pakistan Islamic Republic': 'Pakistan',
  'India Republic': 'India',
  'Bangladesh People\'s Republic': 'Bangladesh',
  'Nepal Federal Democratic Republic': 'Nepal',
  'Bhutan Kingdom': 'Bhutan',
  'Sri Lanka Democratic Socialist': 'Sri Lanka',
  'Maldives Republic': 'Maldives',
  'Afghanistan Islamic Emirate': 'Afghanistan',
  'Mongolia': 'Mongolia',
  'Thailand Kingdom': 'Thailand',
  'Malaysia': 'Malaysia',
  'Singapore Republic': 'Singapore',
  'Indonesia Republic': 'Indonesia',
  'Philippines Republic': 'Philippines',
  'Vietnam Socialist Republic': 'Vietnam',
  'Cambodia Kingdom': 'Cambodia',
  'Laos People\'s Democratic': 'Laos',
  'Myanmar Republic': 'Myanmar',
  'Brunei Sultanate': 'Brunei',
  'Australia Commonwealth': 'Australia',
  'New Zealand': 'New Zealand',
  'Papua New Guinea Independent': 'Papua New Guinea',
  'Fiji Republic': 'Fiji',
  'Samoa Independent': 'Samoa',
  'Tonga Kingdom': 'Tonga',
  'Solomon Islands': 'Solomon Islands',
  'Vanuatu Republic': 'Vanuatu',
  'New Caledonia': 'New Caledonia',
  'French Polynesia': 'French Polynesia',
  'Canada': 'Canada',
  'United States': 'United States',
  'Mexico United Mexican States': 'Mexico',
  'Guatemala Republic': 'Guatemala',
  'Belize': 'Belize',
  'Honduras Republic': 'Honduras',
  'El Salvador Republic': 'El Salvador',
  'Nicaragua Republic': 'Nicaragua',
  'Costa Rica Republic': 'Costa Rica',
  'Panama Republic': 'Panama',
  'Cuba Republic': 'Cuba',
  'Jamaica': 'Jamaica',
  'Haiti Republic': 'Haiti',
  'Dominican Republic': 'Dominican Republic',
  'Bahamas Commonwealth': 'Bahamas',
  'Barbados': 'Barbados',
  'Trinidad and Tobago': 'Trinidad and Tobago',
  'Guyana Co-operative Republic': 'Guyana',
  'Suriname Republic': 'Suriname',
  'French Guiana': 'French Guiana',
  'Brazil Federative Republic': 'Brazil',
  'Colombia Republic': 'Colombia',
  'Venezuela Bolivarian Republic': 'Venezuela',
  'Ecuador Republic': 'Ecuador',
  'Peru Republic': 'Peru',
  'Bolivia Plurinational State': 'Bolivia',
  'Chile Republic': 'Chile',
  'Argentina Argentine Republic': 'Argentina',
  'Paraguay Republic': 'Paraguay',
  'Uruguay Eastern Republic': 'Uruguay',
  'European Union': 'Europe',
  'EU': 'Europe',
  'Scandinavia': 'Sweden',
  'Nordic': 'Sweden',
  'Benelux': 'Netherlands',
  'Caribbean': 'Cuba',
  'Central America': 'Mexico',
  'South America': 'Brazil',
  'Africa': 'Nigeria',
  'Asia': 'China',
  'Oceania': 'Australia',
  'Middle East': 'Saudi Arabia',
  'Arab States': 'Saudi Arabia',
  'GCC': 'Saudi Arabia',
  'ASEAN': 'Singapore',
  'South East Asia': 'Singapore',
  'Pacific Islands': 'Fiji',
  'West Indies': 'Jamaica',
  'Latin America': 'Brazil',
  'Central Asia': 'Kazakhstan',
  'Caucasus': 'Georgia',
  'Baltic States': 'Estonia',
  'Balkans': 'Serbia',
  'East Africa': 'Kenya',
  'West Africa': 'Nigeria',
  'Southern Africa': 'South Africa',
  'North Africa': 'Egypt',
  'South Asia': 'India',
  'East Asia': 'China',
  'Southeast Asia': 'Singapore',
  'North America': 'United States',
  'South America': 'Brazil',
  'Central America': 'Mexico',
  'Western Europe': 'Germany',
  'Eastern Europe': 'Poland',
  'Northern Europe': 'Sweden',
  'Southern Europe': 'Italy'
};

export function extractCountryFromAddress(address) {
  if (!address || typeof address !== 'string') {
    return null;
  }
  
  const addressLower = address.toLowerCase().trim();
  
  for (const [alias, country] of Object.entries(countryNameAliases)) {
    if (addressLower.includes(alias.toLowerCase())) {
      return country;
    }
  }
  
  for (const country of Object.keys(countryCenters)) {
    if (addressLower.includes(country.toLowerCase())) {
      return country;
    }
  }
  
  const countryPatterns = [
    /\b(united\s+states?|u\.s\.a?\.?|america)\b/i,
    /\b(united\s+kingdom|uk|britain)\b/i,
    /\b(china|prc)\b/i,
    /\b(japan)\b/i,
    /\b(germany|deutschland)\b/i,
    /\b(france|français)\b/i,
    /\b(canada)\b/i,
    /\b(australia)\b/i,
    /\b(brazil)\b/i,
    /\b(india)\b/i,
    /\b(russia|russian)\b/i,
    /\b(spain|españa)\b/i,
    /\b(italy|italia)\b/i,
    /\b(mexico)\b/i,
    /\b(south\s+korea|korea)\b/i,
    /\b(netherlands|holland)\b/i,
    /\b(belgium)\b/i,
    /\b(switzerland)\b/i,
    /\b(sweden)\b/i,
    /\b(norway)\b/i,
    /\b(denmark)\b/i,
    /\b(finland)\b/i,
    /\b(poland)\b/i,
    /\b(turkey)\b/i,
    /\b(israel)\b/i,
    /\b(saudi\s+arabia|saudi)\b/i,
    /\b(iran)\b/i,
    /\b(pakistan)\b/i,
    /\b(bangladesh)\b/i,
    /\b(new\s+zealand)\b/i,
    /\b(singapore)\b/i,
    /\b(thailand)\b/i,
    /\b(malaysia)\b/i,
    /\b(indonesia)\b/i,
    /\b(vietnam)\b/i,
    /\b(philippines)\b/i,
    /\b(egypt)\b/i,
    /\b(nigeria)\b/i,
    /\b(south\s+africa)\b/i,
    /\b(uae|united\s+arab\s+emirates)\b/i,
    /\b(argentina)\b/i,
    /\b(chile)\b/i,
    /\b(peru)\b/i,
    /\b(colombia)\b/i,
    /\b(venezuela)\b/i,
    /\b(ecuador)\b/i,
    /\b(bolivia)\b/i,
    /\b(paraguay)\b/i,
    /\b(uruguay)\b/i
  ];

  const countryMap = {
    'united states': 'United States',
    'u.s.a.': 'United States',
    'america': 'United States',
    'united kingdom': 'United Kingdom',
    'uk': 'United Kingdom',
    'britain': 'United Kingdom',
    'china': 'China',
    'prc': 'China',
    'japan': 'Japan',
    'germany': 'Germany',
    'deutschland': 'Germany',
    'france': 'France',
    'canada': 'Canada',
    'australia': 'Australia',
    'brazil': 'Brazil',
    'india': 'India',
    'russia': 'Russia',
    'spain': 'Spain',
    'italy': 'Italy',
    'mexico': 'Mexico',
    'south korea': 'South Korea',
    'korea': 'South Korea',
    'netherlands': 'Netherlands',
    'holland': 'Netherlands',
    'belgium': 'Belgium',
    'switzerland': 'Switzerland',
    'sweden': 'Sweden',
    'norway': 'Norway',
    'denmark': 'Denmark',
    'finland': 'Finland',
    'poland': 'Poland',
    'turkey': 'Turkey',
    'israel': 'Israel',
    'saudi arabia': 'Saudi Arabia',
    'saudi': 'Saudi Arabia',
    'iran': 'Iran',
    'pakistan': 'Pakistan',
    'bangladesh': 'Bangladesh',
    'new zealand': 'New Zealand',
    'singapore': 'Singapore',
    'thailand': 'Thailand',
    'malaysia': 'Malaysia',
    'indonesia': 'Indonesia',
    'vietnam': 'Vietnam',
    'philippines': 'Philippines',
    'egypt': 'Egypt',
    'nigeria': 'Nigeria',
    'south africa': 'South Africa',
    'uae': 'United Arab Emirates',
    'united arab emirates': 'United Arab Emirates',
    'argentina': 'Argentina',
    'chile': 'Chile',
    'peru': 'Peru',
    'colombia': 'Colombia',
    'venezuela': 'Venezuela',
    'ecuador': 'Ecuador',
    'bolivia': 'Bolivia',
    'paraguay': 'Paraguay',
    'uruguay': 'Uruguay'
  };

  for (const pattern of countryPatterns) {
    const match = address.match(pattern);
    if (match) {
      const matchedText = match[0].toLowerCase();
      return countryMap[matchedText] || null;
    }
  }

  const stateCountryMap = {
    'alabama': 'United States',
    'alaska': 'United States',
    'arizona': 'United States',
    'arkansas': 'United States',
    'california': 'United States',
    'colorado': 'United States',
    'connecticut': 'United States',
    'delaware': 'United States',
    'florida': 'United States',
    'georgia': 'United States',
    'hawaii': 'United States',
    'idaho': 'United States',
    'illinois': 'United States',
    'indiana': 'United States',
    'iowa': 'United States',
    'kansas': 'United States',
    'kentucky': 'United States',
    'louisiana': 'United States',
    'maine': 'United States',
    'maryland': 'United States',
    'massachusetts': 'United States',
    'michigan': 'United States',
    'minnesota': 'United States',
    'mississippi': 'United States',
    'missouri': 'United States',
    'montana': 'United States',
    'nebraska': 'United States',
    'nevada': 'United States',
    'new hampshire': 'United States',
    'new jersey': 'United States',
    'new mexico': 'United States',
    'new york': 'United States',
    'north carolina': 'United States',
    'north dakota': 'United States',
    'ohio': 'United States',
    'oklahoma': 'United States',
    'oregon': 'United States',
    'pennsylvania': 'United States',
    'rhode island': 'United States',
    'south carolina': 'United States',
    'south dakota': 'United States',
    'tennessee': 'United States',
    'texas': 'United States',
    'utah': 'United States',
    'vermont': 'United States',
    'virginia': 'United States',
    'washington': 'United States',
    'west virginia': 'United States',
    'wisconsin': 'United States',
    'wyoming': 'United States',
    'nebraska': 'United States',
    'quebec': 'Canada',
    'ontario': 'Canada',
    'british columbia': 'Canada',
    'alberta': 'Canada',
    'manitoba': 'Canada',
    'saskatchewan': 'Canada',
    'nova scotia': 'Canada',
    'new brunswick': 'Canada',
    'manitoba': 'Canada',
    'alberta': 'Canada',
    'british columbia': 'Canada',
    'ontario': 'Canada',
    'quebec': 'Canada',
    'yukon': 'Canada',
    'northwest territories': 'Canada',
    'nunavut': 'Canada',
    'new south wales': 'Australia',
    'victoria': 'Australia',
    'queensland': 'Australia',
    'western australia': 'Australia',
    'south australia': 'Australia',
    'tasmania': 'Australia',
    'northern territory': 'Australia',
    'act': 'Australia',
    'new south wales': 'Australia',
    'victoria': 'Australia',
    'queensland': 'Australia',
    'western australia': 'Australia',
    'south australia': 'Australia',
    'tasmania': 'Australia',
    'hokkaido': 'Japan',
    'tohoku': 'Japan',
    'kanto': 'Japan',
    'chubu': 'Japan',
    'kansai': 'Japan',
    'chugoku': 'Japan',
    'shikoku': 'Japan',
    'kyushu': 'Japan',
    'okinawa': 'Japan',
    'hokkaido': 'Japan',
    'tokyo': 'Japan',
    'osaka': 'Japan',
    'kyoto': 'Japan',
    'hokkaido': 'Japan',
    'aichi': 'Japan',
    'saitama': 'Japan',
    'chiba': 'Japan',
    'kanagawa': 'Japan',
    'niigata': 'Japan',
    'fukushima': 'Japan',
    'gunma': 'Japan',
    'tochigi': 'Japan',
    'ibaraki': 'Japan',
    'yamagata': 'Japan',
    'miyagi': 'Japan',
    'akita': 'Japan',
    'iwate': 'Japan',
    'aomori': 'Japan',
    'fukui': 'Japan',
    'ishikawa': 'Japan',
    'toyama': 'Japan',
    'gifu': 'Japan',
    'nagano': 'Japan',
    'yamanashi': 'Japan',
    'shizuoka': 'Japan',
    'aichi': 'Japan',
    'mie': 'Japan',
    'gifu': 'Japan',
    'shiga': 'Japan',
    'kyoto': 'Japan',
    'osaka': 'Japan',
    'hyogo': 'Japan',
    'nara': 'Japan',
    'wakayama': 'Japan',
    'tottori': 'Japan',
    'shimane': 'Japan',
    'okayama': 'Japan',
    'hiroshima': 'Japan',
    'yamaguchi': 'Japan',
    'tokushima': 'Japan',
    'kagawa': 'Japan',
    'ehime': 'Japan',
    'kochi': 'Japan',
    'fukuoka': 'Japan',
    'saga': 'Japan',
    'nagasaki': 'Japan',
    'kumamoto': 'Japan',
    'oita': 'Japan',
    'miyazaki': 'Japan',
    'kagoshima': 'Japan',
    'okinawa': 'Japan',
    'berlin': 'Germany',
    'bavaria': 'Germany',
    'baden-wurttemberg': 'Germany',
    'hesse': 'Germany',
    'lower saxony': 'Germany',
    'north rhine-westphalia': 'Germany',
    'rhine-land palatinate': 'Germany',
    'saarland': 'Germany',
    'schleswig-holstein': 'Germany',
    'thuringia': 'Germany',
    'hamburg': 'Germany',
    'bremen': 'Germany',
    'mecklenburg-vorpommern': 'Germany',
    'brandenburg': 'Germany',
    'saxony': 'Germany',
    'saxony-anhalt': 'Germany',
    'bayern': 'Germany',
    'berlin': 'Germany',
    'bremen': 'Germany',
    'hamburg': 'Germany',
    'baden-württemberg': 'Germany',
    'bayern': 'Germany',
    'berlin': 'Germany',
    'brandenburg': 'Germany',
    'bremen': 'Germany',
    'hamburg': 'Germany',
    'hessen': 'Germany',
    'mecklenburg-vorpommern': 'Germany',
    'niedersachsen': 'Germany',
    'nordrhein-westfalen': 'Germany',
    'rheinland-pfalz': 'Germany',
    'saarland': 'Germany',
    'sachsen': 'Germany',
    'sachsen-anhalt': 'Germany',
    'schleswig-holstein': 'Germany',
    'thüringen': 'Germany',
    'ile-de-france': 'France',
    'paris': 'France',
    'provence': 'France',
    'cote d\'azur': 'France',
    'brittany': 'France',
    'normandy': 'France',
    'alsace': 'France',
    'lorraine': 'France',
    'aquitaine': 'France',
    'midi-pyrenees': 'France',
    'languedoc-roussillon': 'France',
    'auvergne': 'France',
    'limousin': 'France',
    'poitou-charentes': 'France',
    'centre': 'France',
    'bourgogne': 'France',
    'franche-comte': 'France',
    'pays de la loire': 'France',
    'bretagne': 'France',
    'normandie': 'France',
    'alsace': 'France',
    'lorraine': 'France',
    'champagne-ardenne': 'France',
    'picardie': 'France',
    'haute-normandie': 'France',
    'ile-de-france': 'France',
    'midi-pyrenees': 'France',
    'aquitaine': 'France',
    'languedoc-roussillon': 'France',
    'provence-alpes-cote d\'azur': 'France',
    'corse': 'France',
    'valenciana': 'Spain',
    'catalonia': 'Spain',
    'andalusia': 'Spain',
    'galicia': 'Spain',
    'basque country': 'Spain',
    'castile and leon': 'Spain',
    'castilla-la mancha': 'Spain',
    'extremadura': 'Spain',
    'asturias': 'Spain',
    'cantabria': 'Spain',
    'murcia': 'Spain',
    'balearic islands': 'Spain',
    'canary islands': 'Spain',
    'navarre': 'Spain',
    'la rioja': 'Spain',
    'aragon': 'Spain',
    'madrid': 'Spain',
    'lazio': 'Italy',
    'tuscany': 'Italy',
    'campania': 'Italy',
    'lombardy': 'Italy',
    'veneto': 'Italy',
    'emilia-romagna': 'Italy',
    'piedmont': 'Italy',
    'apulia': 'Italy',
    'sicily': 'Italy',
    'sardinia': 'Italy',
    'calabria': 'Italy',
    'marche': 'Italy',
    'umbria': 'Italy',
    'liguria': 'Italy',
    'trentino-alto adige': 'Italy',
    'friuli-venezia giulia': 'Italy',
    'abruzzo': 'Italy',
    'molise': 'Italy',
    'basilicata': 'Italy',
    'veneto': 'Italy',
    'lombardia': 'Italy',
    'piemonte': 'Italy',
    'emilia-romagna': 'Italy',
    'toscana': 'Italy',
    'umbria': 'Italy',
    'marche': 'Italy',
    'lazio': 'Italy',
    'abruzzo': 'Italy',
    'molise': 'Italy',
    'campania': 'Italy',
    'basilicata': 'Italy',
    'calabria': 'Italy',
    'sicilia': 'Italy',
    'sardegna': 'Italy',
    'veneto': 'Italy',
    'friuli-venezia giulia': 'Italy',
    'trentino-alto adige': 'Italy',
    'liguria': 'Italy',
    'andalucia': 'Spain',
    'aragon': 'Spain',
    'asturias': 'Spain',
    'baleares': 'Spain',
    'canarias': 'Spain',
    'cantabria': 'Spain',
    'castilla-la mancha': 'Spain',
    'castilla y leon': 'Spain',
    'cataluna': 'Spain',
    'comunidad valenciana': 'Spain',
    'extremadura': 'Spain',
    'galicia': 'Spain',
    'madrid': 'Spain',
    'murcia': 'Spain',
    'navarra': 'Spain',
    'pais vasco': 'Spain',
    'rioja': 'Spain',
    'bangkok': 'Thailand',
    'chiang mai': 'Thailand',
    'phuket': 'Thailand',
    'singapore': 'Singapore',
    'kuala lumpur': 'Malaysia',
    'jakarta': 'Indonesia',
    'manila': 'Philippines',
    'hanoi': 'Vietnam',
    'ho chi minh': 'Vietnam',
    'mumbai': 'India',
    'delhi': 'India',
    'bangalore': 'India',
    'chennai': 'India',
    'hyderabad': 'India',
    'ahmedabad': 'India',
    'kolkata': 'India',
    'surat': 'India',
    'pune': 'India',
    'jaipur': 'India',
    'lucknow': 'India',
    'kanpur': 'India',
    'nagpur': 'India',
    'indore': 'India',
    'thane': 'India',
    'bhopal': 'India',
    'visakhapatnam': 'India',
    'vadodara': 'India',
    'faridabad': 'India',
    'ghaziabad': 'India',
    'coimbatore': 'India',
    'ludhiana': 'India',
    'agra': 'India',
    'patna': 'India',
    'kalyan': 'India',
    'mumbai': 'India',
    'new delhi': 'India',
    'karnataka': 'India',
    'maharashtra': 'India',
    'tamil nadu': 'India',
    'andhra pradesh': 'India',
    'telangana': 'India',
    'gujarat': 'India',
    'uttar pradesh': 'India',
    'west bengal': 'India',
    'rajasthan': 'India',
    'madhya pradesh': 'India',
    'kerala': 'India',
    'punjab': 'India',
    'haryana': 'India',
    'chhattisgarh': 'India',
    'odisha': 'India',
    'jharkhand': 'India',
    'assam': 'India',
    'bihar': 'India',
    'uttarakhand': 'India',
    'himachal pradesh': 'India',
    'jammu and kashmir': 'India',
    'goa': 'India',
    'nct of delhi': 'India',
    'andaman and nicobar': 'India',
    'lakshadweep': 'India',
    'puducherry': 'India',
    'chandigarh': 'India',
    'dadra and nagar haveli': 'India',
    'daman and diu': 'India',
    'ladakh': 'India',
    'karachi': 'Pakistan',
    'lahore': 'Pakistan',
    'islamabad': 'Pakistan',
    'rawalpindi': 'Pakistan',
    'hyderabad': 'Pakistan',
    'peshawar': 'Pakistan',
    'quetta': 'Pakistan',
    'multan': 'Pakistan',
    'faisalabad': 'Pakistan',
    'sialkot': 'Pakistan',
    'gujranwala': 'Pakistan',
    'lahore': 'Pakistan',
    'punjab': 'Pakistan',
    'sindh': 'Pakistan',
    'khyber pakhtunkhwa': 'Pakistan',
    'balochistan': 'Pakistan',
    'gilgit-baltistan': 'Pakistan',
    'azad kashmir': 'Pakistan',
    'bangalore': 'India',
    'chennai': 'India',
    'hyderabad': 'India',
    'ahmedabad': 'India',
    'kolkata': 'India',
    'surat': 'India',
    'pune': 'India',
    'jaipur': 'India',
    'lucknow': 'India',
    'kanpur': 'India',
    'nagpur': 'India',
    'indore': 'India',
    'thane': 'India',
    'bhopal': 'India',
    'visakhapatnam': 'India',
    'vadodara': 'India',
    'faridabad': 'India',
    'ghaziabad': 'India',
    'coimbatore': 'India',
    'ludhiana': 'India',
    'agra': 'India',
    'patna': 'India',
    'kalyan': 'India',
    'mumbai': 'India',
    'new delhi': 'India',
    'karnataka': 'India',
    'maharashtra': 'India',
    'tamil nadu': 'India',
    'andhra pradesh': 'India',
    'telangana': 'India',
    'gujarat': 'India',
    'uttar pradesh': 'India',
    'west bengal': 'India',
    'rajasthan': 'India',
    'madhya pradesh': 'India',
    'kerala': 'India',
    'punjab': 'India',
    'haryana': 'India',
    'chhattisgarh': 'India',
    'odisha': 'India',
    'jharkhand': 'India',
    'assam': 'India',
    'bihar': 'India',
    'uttarakhand': 'India',
    'himachal pradesh': 'India',
    'jammu and kashmir': 'India',
    'goa': 'India',
    'nct of delhi': 'India',
    'andaman and nicobar': 'India',
    'lakshadweep': 'India',
    'puducherry': 'India',
    'chandigarh': 'India',
    'dadra and nagar haveli': 'India',
    'daman and diu': 'India',
    'ladakh': 'India',
    'karachi': 'Pakistan',
    'lahore': 'Pakistan',
    'islamabad': 'Pakistan',
    'rawalpindi': 'Pakistan',
    'hyderabad': 'Pakistan',
    'peshawar': 'Pakistan',
    'quetta': 'Pakistan',
    'multan': 'Pakistan',
    'faisalabad': 'Pakistan',
    'sialkot': 'Pakistan',
    'gujranwala': 'Pakistan',
    'lahore': 'Pakistan',
    'punjab': 'Pakistan',
    'sindh': 'Pakistan',
    'khyber pakhtunkhwa': 'Pakistan',
    'balochistan': 'Pakistan',
    'gilgit-baltistan': 'Pakistan',
    'azad kashmir': 'Pakistan',
    'dhaka': 'Bangladesh',
    'chittagong': 'Bangladesh',
    'khulna': 'Bangladesh',
    'rajshahi': 'Bangladesh',
    'barisal': 'Bangladesh',
    'sylhet': 'Bangladesh',
    'rangpur': 'Bangladesh',
    'mymensingh': 'Bangladesh',
    'dhaka division': 'Bangladesh',
    'chittagong division': 'Bangladesh',
    'khulna division': 'Bangladesh',
    'rajshahi division': 'Bangladesh',
    'barisal division': 'Bangladesh',
    'sylhet division': 'Bangladesh',
    'rangpur division': 'Bangladesh',
    'mymensingh division': 'Bangladesh',
    'kathmandu': 'Nepal',
    'pokhara': 'Nepal',
    'lalitpur': 'Nepal',
    'bhaktapur': 'Nepal',
    'biratnagar': 'Nepal',
    'biratnagar': 'Nepal',
    'nepal': 'Nepal',
    'kathmandu valley': 'Nepal',
    'bangalore': 'India',
    'chennai': 'India',
    'hyderabad': 'India',
    'ahmedabad': 'India',
    'kolkata': 'India',
    'surat': 'India',
    'pune': 'India',
    'jaipur': 'India',
    'lucknow': 'India',
    'kanpur': 'India',
    'nagpur': 'India',
    'indore': 'India',
    'thane': 'India',
    'bhopal': 'India',
    'visakhapatnam': 'India',
    'vadodara': 'India',
    'faridabad': 'India',
    'ghaziabad': 'India',
    'coimbatore': 'India',
    'ludhiana': 'India',
    'agra': 'India',
    'patna': 'India',
    'kalyan': 'India',
    'mumbai': 'India',
    'new delhi': 'India',
    'karnataka': 'India',
    'maharashtra': 'India',
    'tamil nadu': 'India',
    'andhra pradesh': 'India',
    'telangana': 'India',
    'gujarat': 'India',
    'uttar pradesh': 'India',
    'west bengal': 'India',
    'rajasthan': 'India',
    'madhya pradesh': 'India',
    'kerala': 'India',
    'punjab': 'India',
    'haryana': 'India',
    'chhattisgarh': 'India',
    'odisha': 'India',
    'jharkhand': 'India',
    'assam': 'India',
    'bihar': 'India',
    'uttarakhand': 'India',
    'himachal pradesh': 'India',
    'jammu and kashmir': 'India',
    'goa': 'India',
    'nct of delhi': 'India',
    'andaman and nicobar': 'India',
    'lakshadweep': 'India',
    'puducherry': 'India',
    'chandigarh': 'India',
    'dadra and nagar haveli': 'India',
    'daman and diu': 'India',
    'ladakh': 'India',
    'karachi': 'Pakistan',
    'lahore': 'Pakistan',
    'islamabad': 'Pakistan',
    'rawalpindi': 'Pakistan',
    'hyderabad': 'Pakistan',
    'peshawar': 'Pakistan',
    'quetta': 'Pakistan',
    'multan': 'Pakistan',
    'faisalabad': 'Pakistan',
    'sialkot': 'Pakistan',
    'gujranwala': 'Pakistan',
    'lahore': 'Pakistan',
    'punjab': 'Pakistan',
    'sindh': 'Pakistan',
    'khyber pakhtunkhwa': 'Pakistan',
    'balochistan': 'Pakistan',
    'gilgit-baltistan': 'Pakistan',
    'azad kashmir': 'Pakistan',
    'dhaka': 'Bangladesh',
    'chittagong': 'Bangladesh',
    'khulna': 'Bangladesh',
    'rajshahi': 'Bangladesh',
    'barisal': 'Bangladesh',
    'sylhet': 'Bangladesh',
    'rangpur': 'Bangladesh',
    'mymensingh': 'Bangladesh',
    'dhaka division': 'Bangladesh',
    'chittagong division': 'Bangladesh',
    'khulna division': 'Bangladesh',
    'rajshahi division': 'Bangladesh',
    'barisal division': 'Bangladesh',
    'sylhet division': 'Bangladesh',
    'rangpur division': 'Bangladesh',
    'mymensingh division': 'Bangladesh',
    'kathmandu': 'Nepal',
    'pokhara': 'Nepal',
    'lalitpur': 'Nepal',
    'bhaktapur': 'Nepal',
    'biratnagar': 'Nepal',
    'biratnagar': 'Nepal',
    'nepal': 'Nepal',
    'kathmandu valley': 'Nepal'
  };

  const words = addressLower.split(/[^a-zA-Z]+/);
  for (const word of words) {
    if (stateCountryMap[word]) {
      return stateCountryMap[word];
    }
  }

  const zipCodePattern = /\b(\d{5}(-\d{4})?)\b/;
  const zipMatch = address.match(zipCodePattern);
  if (zipMatch) {
    const zipCode = zipMatch[1];
    if (parseInt(zipCode) >= 1 && parseInt(zipCode) <= 99950) {
      return 'United States';
    }
  }

  const canadianPostalCode = /\b[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d\b/;
  if (address.match(canadianPostalCode)) {
    return 'Canada';
  }

  const ukPostcode = /\b[A-Z]{1,2}\d[A-Z\d]? [A-Z\d]{3}\b/i;
  if (address.match(ukPostcode)) {
    return 'United Kingdom';
  }

  const australianPostcode = /\b\d{4}\b/;
  const auPostcodeMatch = address.match(australianPostcode);
  if (auPostcodeMatch) {
    const postcode = parseInt(auPostcodeMatch[0]);
    if (postcode >= 1000 && postcode <= 9999) {
      return 'Australia';
    }
  }

  const japanesePostcode = /\b\d{3}-\d{4}\b/;
  if (address.match(japanesePostcode)) {
    return 'Japan';
  }

  return null;
}